/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as DemandasRouteImport } from './routes/demandas'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as IntegracaoRouteImport } from './routes/integracao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandasRoute = DemandasRouteImport.update({
  id: '/demandas',
  path: '/demandas',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracaoRoute = IntegracaoRouteImport.update({
  id: '/integracao',
  path: '/integracao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof ClientesRoute
  '/demandas': typeof DemandasRoute
  '/equipe': typeof EquipeRoute
  '/integracao': typeof IntegracaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof ClientesRoute
  '/demandas': typeof DemandasRoute
  '/equipe': typeof EquipeRoute
  '/integracao': typeof IntegracaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof ClientesRoute
  '/demandas': typeof DemandasRoute
  '/equipe': typeof EquipeRoute
  '/integracao': typeof IntegracaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/auth'
    | '/clientes'
    | '/demandas'
    | '/equipe'
    | '/integracao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/auth'
    | '/clientes'
    | '/demandas'
    | '/equipe'
    | '/integracao'
  id:
    | '__root__'
    | '/'
    | '/ajuda'
    | '/auth'
    | '/clientes'
    | '/demandas'
    | '/equipe'
    | '/integracao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaRoute: typeof AjudaRoute
  AuthRoute: typeof AuthRoute
  ClientesRoute: typeof ClientesRoute
  DemandasRoute: typeof DemandasRoute
  EquipeRoute: typeof EquipeRoute
  IntegracaoRoute: typeof IntegracaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandas': {
      id: '/demandas'
      path: '/demandas'
      fullPath: '/demandas'
      preLoaderRoute: typeof DemandasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracao': {
      id: '/integracao'
      path: '/integracao'
      fullPath: '/integracao'
      preLoaderRoute: typeof IntegracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaRoute: AjudaRoute,
  AuthRoute: AuthRoute,
  ClientesRoute: ClientesRoute,
  DemandasRoute: DemandasRoute,
  EquipeRoute: EquipeRoute,
  IntegracaoRoute: IntegracaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
